# elasticsearch的使用
server:
  port: 9070
  servlet:
    context-path: /elastic
spring:
  elasticsearch:
    #可以配置多个 urls是一个list
    uris: http://172.16.75.110:9200
    username: elastic
    password: abcd@123456
    #连接超时 10秒  默认1秒
    connection-timeout: 10
  data:
    elasticsearch:
      repositories:
        enabled: true