<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.example</groupId>
        <artifactId>springboot-collection-jdk21</artifactId>
        <version>1.0</version>
    </parent>

    <artifactId>springboot-ai</artifactId>
    <packaging>pom</packaging>

    <name>springboot-ai</name>
    <modules>
        <module>springboot-langchain4j</module>
        <module>springboot-spring-ai</module>
        <module>springboot-ai-alibaba-items</module>
    </modules>

    <properties>
        <spring-ai.version>1.0.0</spring-ai.version>
        <langchain4j.version>1.0.0</langchain4j.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <!--spring-ai 实现方式-->
            <dependency>
                <groupId>org.springframework.ai</groupId>
                <artifactId>spring-ai-bom</artifactId>
                <version>${spring-ai.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!--langchain4j的方式-->
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-bom</artifactId>
                <version>${langchain4j.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
