#配置服务的信息
server:
  port: 8989
spring:
  profiles:
    active: dev
  application:
    name: springboot-mybatis-plus
knife4j:
  enable: true
  setting:
    enable-swagger-models: true
    language: zh_cn
    swagger-model-name: 实体类
logging:
  level:
    web: error